name: verify and push
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Check out branch
      run: |
        git checkout $(git rev-list --parents -n 1 HEAD | cut -d' ' -f3)
    - name: Verify
      run: |
        python3 verify.py
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
